FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy application files
COPY . .

# Expose Gateway Port
EXPOSE 3000

# Start Express Server
CMD ["node", "backend/index.js"]
